create database projetoIndividual;

use projetoIndividual;

create table cadastro (
idCadastro int auto_increment primary key,
nome varchar(45),
email varchar(100),
senha varchar(45),
fkCampeao int,
fkComentario int,
foreign key (fkCampeao) references votacao(idCampeao),
foreign key (fkComentario) references comentario(idComentario)
);

create table votacao(
idCampeao int auto_increment primary key,
nomeCampeao varchar(45),
votos int
);

create table comentario(
idComentario int auto_increment primary key,
comentario text
);

select * from comentario;

insert into votacao(nomeCampeao, votos) values 
	("Aatrox", 0),
	("Ahri", 0),
	("Akali", 0),
	("Akshan", 0),
	("Alistar", 0),
	("Amumu", 0),
	("Anivia", 0),
	("Annie", 0),
	("Aphelios", 0),
	("Ashe", 0),
	("Aurelion Sol", 0),
	("Azir", 0),
	("Bardo", 0),
	("Bel'veth", 0),
	("Blitzcrank", 0),
	("Brand", 0),
	("Braum", 0),
	("Caitlyn", 0),
	("Camille", 0),
	("Cassiopeia", 0),
	("Cho'gath", 0),
	("Corki", 0),
	("Darius", 0),
	("Diana", 0),
	("Dr. mundo", 0),
	("Draven", 0),
	("Ekko", 0),
	("Elise", 0),
	("Evelynn", 0),
	("Ezreal", 0),
	("Fiddlesticks", 0),
	("Fiora", 0),
	("Fizz", 0),
	("Galio", 0),
	("Gangplank", 0),
	("Garen", 0),
	("Gnar", 0),
	("Gragas", 0),
	("Graves", 0),
	("Gwen", 0),
	("Hecarim", 0),
	("Heimerdinger", 0),
	("Illaoi", 0),
	("Irelia", 0),
	("Ivern", 0),
	("Janna", 0),
	("Jarvan IV", 0),
	("Jax", 0),
	("Jayce", 0),
	("Jhin", 0),
	("Jinx", 0),
	("K'sante", 0),
	("Kai'sa", 0),
	("Kalista", 0),
	("Karma", 0),
	("Karthus", 0),
	("Kassadin", 0),
	("Katarina", 0),
	("Kayle", 0),
	("Kayn", 0),
	("Kennen", 0),
	("Kha'zix", 0),
	("Kindred", 0),
	("Kled", 0),
	("Kog'maw", 0),
	("Leblanc", 0),
	("Lee sin", 0),
	("Leona", 0),
	("Lilia", 0),
	("Lissandra", 0),
	("Lucian", 0),
	("Lulu", 0),
	("Lux", 0),
	("Malphite", 0),
	("Malzahar", 0),
	("Maokai", 0),
	("Master Yi", 0),
	("Miss Fortune", 0),
	("Mordekaiser", 0),
	("Morgana", 0),
	("Nami", 0),
	("Nasus", 0),
	("Nautilus", 0),
	("Neeko", 0),
	("Nidalee", 0),
	("Nilah", 0),
	("Nocturne", 0),
	("Nunu e Will", 0),
	("Olaf", 0),
	("Orianna", 0),
	("Ornn", 0),
	("Pantheon", 0),
	("Poppy", 0),
	("Pyke", 0),
	("Qiyana", 0),
	("Quinn", 0),
	("Rakan", 0),
	("Rammus", 0),
	("Rek'sai", 0),
	("Rell", 0),
	("Renata Glasc", 0),
	("Renekton", 0),
	("Rengar", 0),
	("Riven", 0),
	("Rumble", 0),
	("Ryze", 0),
	("Samira", 0),
	("Sejuani", 0),
	("Senna", 0),
	("Seraphine", 0),
	("Sett", 0),
	("Shaco", 0),
	("Shen", 0),
	("Shyvana", 0),
	("Singed", 0),
	("Sion", 0),
	("Sivir", 0),
	("Skarner", 0),
    ("Sona", 0),
	("Soraka", 0),
	("Swain", 0),
	("Sylas", 0),
	("Syndra", 0),
	("Tahm Kench", 0),
	("Taliyah", 0),
	("Talon", 0),
	("Taric", 0),
	("Teemo", 0),
	("Thresh", 0),
	("Tristana", 0),
	("Trundle", 0),
	("Tryndamere", 0),
	("Twisted Fate", 0),
	("Twitch", 0),
	("Udyr", 0),
	("Urgot", 0),
	("Varus", 0),
	("Vayne", 0),
	("Veigar", 0),
	("Vel'koz", 0),
	("Vex", 0),
	("Vi", 0),
	("Viego", 0),
	("Viktor", 0),
	("Vladimir", 0),
	("Volibear", 0),
	("Warwick", 0),
	("Wukong", 0),
	("Xayah", 0),
	("Xerath", 0),
	("Xin zhao", 0),
	("Yasuo", 0),
	("Yone", 0),
	("Yorick", 0),
	("Yummi", 0),
	("Zac", 0),
	("Zed", 0),
	("Zeri", 0),
	("Ziggs", 0),
	("Zilean", 0),
	("Zoe", 0),
	("Zyra", 0);